### ISSUE TITLE
os x 10.8 no events are firing

### ISSUE THREAD

**Issue by docwhat** [thibaudgg/rb-fsevent#41]
I have the following test code:

```
require 'rb-fsevent'

dir = File.expand_path '../..', __FILE__

fsevent = FSEvent.new
fsevent.watch dir do |directories|
  puts "Detected change inside: #{directories.inspect}"
end
fsevent.run
```

If I do a 'touch' inside the directory that contains the script, I don't get any output.

    rb-fsevent: 0.9.3
    ruby 1.9.3-p286
    OSX 10.8.2
    RVM 1.17.7

**Comment by ttilley** [comment]
a workaround has been added to the latest rb-fsevent release. please upgrade (and read the updated README for more info).
