### ISSUE TITLE
Ctrl-C behaviour?

### ISSUE THREAD

**Issue by ioquatix** [thibaudgg/rb-fsevent#47]
Hi,

When entering `fsevent.run`, if the user hits ctrl-c the exception is not propagated as one might expect.

Expected when user press ctrl-c or process killed with sigint, that `fsevent.run` would internally raise `Interrupt`.

Actual result: `fsevent.run` returns with no special information about interrupt.

**Comment by ttilley** [comment]
you already know what's up with me closing this bug. smiles, happiness, sunshine, and all that other good stuff.
