### ISSUE TITLE
spec/fixtures includes garbage

### ISSUE THREAD

**Issue by kaneda** [thibaudgg/rb-fsevent#52]
``` bash
drwxr-xr-x 3 jbegleiter staff 102 Aug  8 12:55 custom 'path
drwxr-xr-x 4 jbegleiter staff 136 Aug  8 13:04 folder1

./custom 'path:

./folder1:
-rw-r--r-- 1 jbegleiter staff   0 Aug  8 12:55 file1.txt
drwxr-xr-x 3 jbegleiter staff 102 Aug  8 13:04 folder2

./folder1/folder2:
-rw-r--r-- 1 jbegleiter staff 0 Aug  8 12:55 file2.txt
```

The single-quote in the name actually screws up my mvn package, which I've had to explicitly ignore

**Comment by abtreece** [comment]
+1

**Comment by ttilley** [comment]
three things here...

1. that funky as hell path is to test that things still work with funky as hell paths, as they are perfectly valid paths on the underlying filesystem and need to be handled
2. the test suite as a whole will be completely replaced in the near future as the various projects under the Guard/Listen tree are consolidated to use a (mostly) shared test suite
3. this library will be deprecated within a few months from now in favor of a version that makes use of FFI which will resolve a number of long-standing bugs and almost certainly make life easier for you as an mvn/jruby/etc user. 

I do need to close this bug as essentially will-not-fix but keep an eye on things as `listen-fsevents` will be **much** more suited to your usage. Please be patient with me for a little bit longer... I'm genuinely sorry these paths are such a PITA for you.
