### ISSUE TITLE
register_with_server: ERROR

### ISSUE THREAD

**Issue by obromios** [thibaudgg/rb-fsevent#54]
I am using rails, guard, fb-fsevent on Mac OSX to trigger rspec when I change a test or code. It works well, but I often get the following sort of message

```
fsevent_watch[4227] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR:    f2d_register_rpc() => (null) (-21)
when I start guard with bundle exec guard.
```

I can often fix this by closing a couple of unneeded applications, but in the end I have to reboot the system. It appears to be caused by watching too many files, so as my application grows it becomes worse. Any suggestions on how to fix this? The relevant version numbers are:

rails 4.2.0, guard 2.6.1, fb-fsevent 0.9.1 on Mac OSX 10.10.1.  I have asked this question on stackoverflow [here](http://stackoverflow.com/questions/29343324/guard-triggering-intermittently) but have received no answer.

**Comment by beechnut** [comment]
I am experiencing the same error, using Rails 4.2.5.1, Ruby 2.3.1, rb-fsevent 0.9.7, on Mac OS X 10.10.4 (14E46).

I experienced a Ruby crash, reinstalled 2.3.1, and this began happening.

```
$ guard
13:24:50 - INFO - Guard::Minitest 2.4.4 is running, with Minitest::Unit 5.8.4!
13:24:50 - INFO - Guard is now watching at 'my/app/directory'
[1] guard(main)> 2016-05-13 13:24 fsevent_watch[83601] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
```

**Comment by GoodVincentTu** [comment]
My project occurs this same errors when i messed up with the sunspot and solr engine. Is there any way can walkaround?

**Comment by ttilley** [comment]
...to be honest, I think this is partially related to the bug where instances of fsevent_watch weren't dying, remaining resident, and largely screwing things up you (not to mention destroying CPU resources). 

This library is going to be largely deprecated within the next few months in favor of a version making use of FFI. If what I think is happening is actually happening, then without the subprocess the issue might go away.

Either way, I need to close this bug right now as will-not-fix. Please check back when guard migrates to using `listen-fsevents` and re-file if i'm completely wrong about the source of this bug.
