### ISSUE TITLE
Jruby shutdown Error

### ISSUE THREAD

**Issue by mitchrodrigues** [thibaudgg/rb-fsevent#55]
When terming the server rb-fsevent fires this backtrace on Jruby-1.7.19. This is caused by a Process.kill on a pid that no longer exists, this issue could be native jruby. This occurs when terming or restarting a process, which calls stop.

I have a patch. Will submit it for your review if you guys would like.

        E, [2015-09-01T10:02:39.921000 #57325] ERROR -- : run() in thread failed: No such process - No such process:\n org/jruby/RubyProcess.java:979:in kill org/jruby/RubyProcess.java:889:in `kill'
        /Users/mrodrigues/.rvm/gems/jruby-1.7.19@jms/gems/rb-fsevent-0.9.5/lib/rb-fsevent/fsevent.rb:55:in `stop'
        /Users/mrodrigues/.rvm/gems/jruby-1.7.19@jms/gems/rb-fsevent-0.9.5/lib/rb-fsevent/fsevent.rb:50:in `run'
        /Users/mrodrigues/.rvm/gems/jruby-1.7.19@jms/gems/listen-3.0.3/lib/listen/adapter/darwin.rb:41:in `_run'
        /Users/mrodrigues/.rvm/gems/jruby-1.7.19@jms/gems/listen-3.0.3/lib/listen/adapter/base.rb:78:in `start'
        org/jruby/RubyProc.java:271:in `call'
        /Users/mrodrigues/.rvm/gems/jruby-1.7.19@jms/gems/listen-3.0.3/lib/listen/internals/thread_pool.rb:6:in `add'\n\ncalled from:\n /Users/mrodrigues/.rvm/gems    /jruby-1.7.19@jms/gems/listen-3.0.3/lib/listen/backend.rb:26:in `start'

**Comment by thibaudgg** [comment]
Fixed by #56, version 0.9.6 released. Thanks!

**Comment by ttilley** [comment]
I didn't actually see this until 4 days after it was submitted, but I still want to thank you for the patch. It's greatly appreciated. :+1:
