### ISSUE TITLE
Include Gemfile hints

### ISSUE THREAD

**Issue by caesarsol** [thibaudgg/rb-fsevent#57]
Wouldn't be a good idea to write in the README a suggestion on how to include the gem in the Gemfile?

The problem exists in multi-platform configurations, as it's not unusual to develop on OS X machines and deploy on Linux ones. We don't want Bundler to try to install rb-fsevent on Linux.

For example, I used:

```
gem 'rb-fsevent', install_if: ->() { `uname` =~ /darwin/i }
```

(And by the way, do you think this is a good approach?)

Thanks!

**Comment by ttilley** [comment]
typically, you don't want to depend directly on rb-fsevent, rb-inotify, or any of the others yourself. you want to depend on a generic solution that integrates them all and makes life easier for you. good options are FSSM and Listen. FSSM is mine, but unmaintained for some time now... Listen is from the awesome guys at the Guard group (of which @thibaudgg is a main contributor). 

Listen: https://github.com/guard/listen
FSSM: https://github.com/ttilley/fssm

If you need an example of integrating with these, compass and sass were my initial use case for writing much of this code, and Guard was @thibaudgg's. All three are well documented projects.

**Comment by caesarsol** [comment]
Oh, that's very interesting!

I found the Gemfile line in a project I'm working with, I'll let the maintainers know of this.

Thanks!
