### ISSUE TITLE
single quote in a file name

### ISSUE THREAD

**Issue by rlh100** [thibaudgg/rb-fsevent#58]
This package creats a gem that has a directory not only with a space, bad news for Linuxs user, but also has a single quote in it:
/usr/local/share/gems/gems/rb-fsevent-0.9.6/spec/fixtures/custom*

This gem was auto installed when I installed a jekyll theme.

I am fairly certain it is yours:
/usr/local/share/gems/gems/rb-fsevent-0.9.6//README.md
https://codeclimate.com/badge.png)](https://codeclimate.com/github/thibaudgg/rb-fsevent)
https://api.coderwall.com/ttilley/endorsecount.png)](https://coderwall.com/ttilley)

**Comment by thibaudgg** [comment]
Hey Robert, thanks for the issue.
I'll remove the spec files from the gem, it should be fixed in the next release (0.9.7).
