### ISSUE TITLE
rb-fsevent 0.9.8 specs warnings

### ISSUE THREAD

**Issue by iforgetmyname** [thibaudgg/rb-fsevent#63]
When I've updated to 0.9.8 though bundle, jekyll tells me as follows:

> WARN: Unresolved specs during Gem::Specification.reset:
>       rb-fsevent (>= 0.9.3)
> WARN: Clearing out unresolved specs.
> 

I've tried to reinstall rb-fsevent through gem, but it still refuses to work.

**Comment by thibaudgg** [comment]
@iforgetmyname did you also forget to add a proper description? :trollface:

**Comment by iforgetmyname** [comment]
Sorry, i'm a freshman. Where can i add a proper description?

**Comment by thibaudgg** [comment]
Seems like [a rubygems issue](https://github.com/rubygems/rubygems/issues/1070), could you try updating it (`gem update --system`).

**Comment by iforgetmyname** [comment]
ok, many thanks.
