### ISSUE TITLE
Test passes when run for the first time, but fails after that

### ISSUE THREAD

**Issue by akashani62** [thibaudgg/rb-fsevent#64]
File `bin/fsevent_watch` gets deleted after the first run, but never gets recreated .

**Comment by ttilley** [comment]
this library is being deprecated in favor of a version that makes use of FFI, and so I am closing old issues as will-not-fix. rejoice in the fact that fsevent_watch in the new version will be purely ruby and entirely unused unless you need it for debugging. please be patient with me just a short while longer.
