### ISSUE TITLE
bin/fsevent_watch not getting regenerated

### ISSUE THREAD

**Issue by akashani62** [thibaudgg/rb-fsevent#67]
When run the test, first time passes perfectly, but it deletes `bin/fsevent_watch` and never regenerate that again. so the second test and on fails.

**Comment by ttilley** [comment]
this library is being deprecated in favor of a version that makes use of FFI, and so I am closing old issues as will-not-fix. rejoice in the fact that fsevent_watch in the new version will be purely ruby and entirely unused unless you need it for debugging. please be patient with me just a short while longer.
