### ISSUE TITLE
Running worker failed error after rails server started

### ISSUE THREAD

**Issue by ShalaQweghen** [thibaudgg/rb-fsevent#76]
Stack:
`Ruby 2.4.1`
`Rails 5.1.2`

Error:
```
E, [2017-06-30T17:51:34.978441 #83263] ERROR -- : fsevent: running worker failed: wrong number of arguments (given 2, expected 1):/Users/shala/.rvm/gems/ruby-2.4.1/gems/listen-3.1.5/lib/listen/adapter/base.rb:41:in `block (2 levels) in configure'
/Users/shala/.rvm/gems/ruby-2.4.1/gems/rb-fsevent-0.10.1/lib/rb-fsevent/fsevent.rb:75:in `run'
/Users/shala/.rvm/gems/ruby-2.4.1/gems/listen-3.1.5/lib/listen/adapter/darwin.rb:71:in `_run_worker'
/Users/shala/.rvm/gems/ruby-2.4.1/gems/listen-3.1.5/lib/listen/adapter/darwin.rb:55:in `_run'
/Users/shala/.rvm/gems/ruby-2.4.1/gems/listen-3.1.5/lib/listen/adapter/base.rb:78:in `block in start'
/Users/shala/.rvm/gems/ruby-2.4.1/gems/listen-3.1.5/lib/listen/internals/thread_pool.rb:6:in `block in add' called from: /Users/shala/.rvm/gems/ruby-2.4.1/gems/listen-3.1.5/lib/listen/adapter/darwin.rb:70:in `_run_worker'
/Users/shala/.rvm/gems/ruby-2.4.1/gems/listen-3.1.5/lib/listen/adapter/darwin.rb:55:in `_run'
/Users/shala/.rvm/gems/ruby-2.4.1/gems/listen-3.1.5/lib/listen/adapter/base.rb:78:in `block in start'
/Users/shala/.rvm/gems/ruby-2.4.1/gems/listen-3.1.5/lib/listen/internals/thread_pool.rb:6:in `block in add'
```

**Comment by naturtrunken** [comment]
Same thing here with Ruby 2.4.0, Rails 5.1.1 in macOS 10.12.5. The culprit seems to be the change in commit 2be35f19fc6691faef5b28d702093ddd2b4834ea in the callback call where is now a second parameter.

Unfortunately I didn't unterstand enough of this code to fix it; so I made a workaround for me by adding the last working version with `gem 'rb-fsevent', '= 0.9.8'` in the Gemfile.

https://github.com/thibaudgg/rb-fsevent/blob/f6492c7f5fdf9cc81ff9b69dce387fc2d3fff1b7/lib/rb-fsevent/fsevent.rb#L75

**Comment by ttilley** [comment]
Have you ever put rice in the rice maker and forget to turn it on just to realize two hours later why your rice isn't done? This is like that, only in public and way worse.

I should be checking the callback arity. 🤦‍♂️ 

Unrelated, but github's facepalm emotes are apparently gendered. Hadn't needed to know before now.

**Comment by ttilley** [comment]
ping @ioquatix - all of my local tests pass and it's seriously breaking my mind here. the tests themselves still only use ONE parameter in the callback... just like everyone else in the world as of the 0.10.0 release. From the spec:

```ruby
  before(:each) do
    @results = []
    @fsevent = FSEvent.new
    @fsevent.watch @fixture_path.to_s, {:latency => 0.3, :no_defer => true} do |paths|
      @results += paths
    end
  end
```

Now... I know the fix here. It's an easy fix. Just do something to the effect of:

```ruby
case callback.arity
when 1 callback.call(modified_paths)
when 2 callback.call(modified_paths, decoded)
end
```

But WHY don't my tests break when apparently listen does?! I need to understand what's going on here. I'm using what is likely the same ruby as the initial reporter as my primary ruby: `ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]`.

The code is running in a new thread in the tests, but that isn't swallowing errors because I actually check the `@results` array in the tests!! It's obviously running and succeeding. Where are my tests lacking to not have caught this?

**Comment by ioquatix** [comment]
can you give me a bit more context?

**Comment by ioquatix** [comment]
With my limited understanding of what is going on... did you know that lambda and proc have different behaviour w.r.t. arity?

```ruby
doot = proc do |a|
	puts a
end

doot.call(10)
doot.call(10, 20) # okay, 20 is ignored


doot = lambda do |a|
	puts a
end

doot.call(10)
doot.call(10, 20) # fails
```

**Comment by ttilley** [comment]
To anyone currently experiencing this issue, I apologise. I could release the above fix about checking block arity, but without understanding why my tests pass i'm going to lose my mind. 

@ioquatix - The API takes a block as a callback and, until now, it has always been called with exactly one parameter. Now I call it with two parameters... but in my testing, even if you pass in a block with just one parameter caught and used, it still worked. This led me to believe you could safely ignore the second parameter and the change wouldn't break any existing code. Obviously, I'm wrong.

**Comment by ioquatix** [comment]
This can occur in the following situation:

```ruby

def invoke_callback(&block)
	block.call(10, 20)
end

invoke_callback do |a|
	puts 10
end

doot = lambda do |a|
	puts a
end

invoke_callback(&doot) # fails
```

**Comment by ttilley** [comment]
@ioquatix - is listen using lambda instead of just passing an automatic block->proc conversion? that would certainly explain it. and the above mentioned fix would also certainly fix the problem by checking block arity first.

**Comment by ioquatix** [comment]
I actually don't know what's being passed in but you could to some `puts` debugging and take a look.

```ruby
> puts doot
#<Proc:0x007fcfcfa9acf8@(pry):22 (lambda)>
```

Additionally, I did a quick google and found https://stackoverflow.com/questions/16197082/how-to-convert-method-or-lambda-to-non-lambda-proc which seems to imply the best work-around is to check `#arity`. Blegh.

**Comment by ttilley** [comment]
ruby sure has some fun edge cases. that's for sure.

**Comment by ioquatix** [comment]
A lambda behaves like a method, while a proc behaves like a block. Yes, it probably looks like an edge case from where you are right now, but it's not really.

**Comment by ttilley** [comment]
I know it's blegh, but I also know it'll work because I've seen that pattern all over the place. like... FactoryGirl has arity checks everywhere.

I guess it's time to add an arity check. 🤷‍♂️ 

Thanks for the enlightening info @ioquatix. I'll have to add tests specifically using lambdas.

**Comment by ioquatix** [comment]
There are also some differences w.r.t. return - you can't return from a proc but I think you can from a lambda, and the flow control is a bit different.. make sure you use ensure for managing resources when they go out of scope if necessary.

**Comment by ttilley** [comment]
v0.10.2 should fix this. Leaving the bug open so that reporters can confirm.

**Comment by ioquatix** [comment]
@ttilley Don't stress too much, I fucked up too on my first update to rb-inotify :D https://github.com/guard/rb-inotify/issues/68

**Comment by ioquatix** [comment]
It's hard when you have 10,000 downloads a day lol

**Comment by ttilley** [comment]
this is, quite possibly, my most embarrassing bug... breaking the number one user of the API (listen).  Yet another reason why we should all adopt your central test suite idea, @ioquatix.
