### ISSUE TITLE
Few releases wasn't pushed to rubygems.org. SO CI is failing

### ISSUE THREAD

**Issue by fanantoxa** [thibaudgg/rb-fsevent#78]
Releases: `v0.10.0` and `v0.10.1` missing on rubygems.org. SO It breaks CI with error:
```
Could not find rb-fsevent-0.10.1 in any of the sources
```

**Comment by ttilley** [comment]
these were yanked due to breaking their biggest users

**Comment by fanantoxa** [comment]
@ttilley oh) So what how does look compulsory update.

**Comment by ttilley** [comment]
i'm not sure i understood that last sentence?
