### ISSUE TITLE
Read event

### ISSUE THREAD

**Issue by asok** [thibaudgg/rb-fsevent#84]
Hi,
I just wanted to make an inquiry - if it is possible to listen to a "read" event on a given file or a file within a given directory?

**Comment by thibaudgg** [comment]
Hi @asok, no "read" event isn't supported, only file creation and update are.

**Comment by asok** [comment]
Do you reckon it is something hard to implement?

**Comment by thibaudgg** [comment]
fsevent doesn't expose read events, so you must find another way.

Maybe https://stackoverflow.com/questions/3161499/osx-hook-file-read-event can help you.

**Comment by asok** [comment]
Thanks a lot.
